##===- projects/sample/tools/sample/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=kal

#CFLAGS=$CFLAGS -std=c++11

#
# List libraries that we'll need
# We use LIBS because sample is a dynamic library.
#
USEDLIBS = sample.a

LINK_COMPONENTS = all

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

